'use strict'

// TODO: Add @types folder

module.exports = [
  '__*__',
  '_config.yml',
  '.*',
  '*.js.map',
  '*.map.json',
  '*.opts',
  'appveyor.yml',
  'AUTHORS*',
  'changelog*',
  'CHANGELOG*',
  'CHANGES*',
  'circle.yml',
  'CONTRIBUTING.md',
  'contributing*',
  'Contributing*',
  'CONTRIBUTING*',
  'contribution*',
  'Contribution*',
  'CONTRIBUTION*',
  'CONTRIBUTORS',
  'docs/*',
  'eslint',
  'example.*',
  'example/*',
  'examples',
  'Gruntfile.js',
  'gulpfile.js',
  'Gulpfile.js',
  'history.md',
  'history*',
  'History*',
  'HISTORY*',
  'htmllint.js',
  'jest.config.js',
  'karma.conf.js',
  'license*',
  'License*',
  'LICENSE*',
  'Makefile',
  'node_modules/*',
  'npm-*.log',
  'package-lock.json',
  'PULL_REQUEST_TEMPLATE*',
  'readme*',
  'Readme*',
  'README*',
  'stylelint*',
  'test*',
  'tsconfig.json',
  'yarn-*.log',
  'yarn.lock'
]
